# Generated by Django 4.1.1 on 2022-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyup', '0002_alter_pages_options_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
