# Generated by Django 4.0.7 on 2022-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyup', '0005_indexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Основная страница', 'verbose_name_plural': 'Основные страницы'},
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
