# Generated by Django 4.0.7 on 2023-02-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyup', '0007_alter_cards_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='unit',
            field=models.CharField(blank=True, choices=[('0', 'Грамм'), ('1', 'Килограмм'), ('2', 'Штуку')], max_length=11),
        ),
    ]
