# Generated by Django 4.0.7 on 2023-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyup', '0008_cards_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='unit',
            field=models.CharField(blank=True, choices=[('Грамм', 'Грамм'), ('Килограмм', 'Килограмм'), ('Штуку', 'Штуку')], max_length=11),
        ),
    ]
