# Generated by Django 4.0.7 on 2023-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyup', '0009_alter_cards_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='used_price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='unit',
            field=models.CharField(blank=True, choices=[('грамм', 'Грамм'), ('килограмм', 'Килограмм'), ('штуку', 'Штуку')], max_length=11),
        ),
    ]
